"""update_ontario_chunks_with_hierarchy

Revision ID: 17fe0f09d9c9
Revises: 60d4a738e6e9
Create Date: 2025-09-19 22:25:43.306882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fe0f09d9c9'
down_revision: Union[str, Sequence[str], None] = '60d4a738e6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ontario_chunks', sa.Column('division', sa.String(length=50), nullable=True))
    op.add_column('ontario_chunks', sa.Column('chunk_type', sa.String(length=20), nullable=False, server_default='article'))
    op.add_column('ontario_chunks', sa.Column('title', sa.String(length=200), nullable=True))
    op.alter_column('ontario_chunks', 'reference',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index(op.f('ix_ontario_chunks_chunk_type'), 'ontario_chunks', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_ontario_chunks_division'), 'ontario_chunks', ['division'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontario_chunks_division'), table_name='ontario_chunks')
    op.drop_index(op.f('ix_ontario_chunks_chunk_type'), table_name='ontario_chunks')
    op.alter_column('ontario_chunks', 'reference',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('ontario_chunks', 'title')
    op.drop_column('ontario_chunks', 'chunk_type')
    op.drop_column('ontario_chunks', 'division')
    # ### end Alembic commands ###
