"""add ontario_chunks table

Revision ID: 60d4a738e6e9
Revises: abdd5526dc4b
Create Date: 2025-09-14 17:34:56.855442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d4a738e6e9'
down_revision: Union[str, Sequence[str], None] = 'abdd5526dc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontario_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('part', sa.String(length=10), nullable=True),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('subsection', sa.String(length=10), nullable=True),
    sa.Column('article', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontario_chunks_article'), 'ontario_chunks', ['article'], unique=False)
    op.create_index(op.f('ix_ontario_chunks_part'), 'ontario_chunks', ['part'], unique=False)
    op.create_index(op.f('ix_ontario_chunks_reference'), 'ontario_chunks', ['reference'], unique=False)
    op.create_index(op.f('ix_ontario_chunks_section'), 'ontario_chunks', ['section'], unique=False)
    op.create_index(op.f('ix_ontario_chunks_subsection'), 'ontario_chunks', ['subsection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontario_chunks_subsection'), table_name='ontario_chunks')
    op.drop_index(op.f('ix_ontario_chunks_section'), table_name='ontario_chunks')
    op.drop_index(op.f('ix_ontario_chunks_reference'), table_name='ontario_chunks')
    op.drop_index(op.f('ix_ontario_chunks_part'), table_name='ontario_chunks')
    op.drop_index(op.f('ix_ontario_chunks_article'), table_name='ontario_chunks')
    op.drop_table('ontario_chunks')
    # ### end Alembic commands ###
