"""Drop total_sections and completed_sections from Project

Revision ID: 9f05dabcafd0
Revises: ca6d91d4ac78
Create Date: 2025-10-28 20:10:21.952951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f05dabcafd0'
down_revision: Union[str, Sequence[str], None] = 'ca6d91d4ac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'total_sections')
    op.drop_column('project', 'completed_sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('completed_sections', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('project', sa.Column('total_sections', sa.INTEGER(), server_default=sa.text("'27'"), nullable=False))
    # ### end Alembic commands ###
