"""Add section tracking columns to Project

Revision ID: ca6d91d4ac78
Revises: 495b4d75fc56
Create Date: 2025-10-28 20:05:52.271327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca6d91d4ac78'
down_revision: Union[str, Sequence[str], None] = '495b4d75fc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('current_section', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='3.01'))
    op.add_column('project', sa.Column('total_sections', sa.Integer(), nullable=False, server_default='27'))
    op.add_column('project', sa.Column('completed_sections', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'completed_sections')
    op.drop_column('project', 'total_sections')
    op.drop_column('project', 'current_section')
    # ### end Alembic commands ###
