"""Add due_date, total_sections, and completed_sections to Project model

Revision ID: ddd6a45e6bc2
Revises: 9f05dabcafd0
Create Date: 2025-11-10 23:06:30.529350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd6a45e6bc2'
down_revision: Union[str, Sequence[str], None] = '9f05dabcafd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('total_sections', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('project', sa.Column('completed_sections', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'completed_sections')
    op.drop_column('project', 'total_sections')
    op.drop_column('project', 'due_date')
    # ### end Alembic commands ###
